import type { ProgressivePromptDefinition } from "./types";

export const PROGRESSIVE_PROMPTS: ProgressivePromptDefinition[] = [
  {
    action: "first_query_completed",
    answers: [
      { id: "manufacturing", label: "Manufacturing", writes: [{ key: "industry", value: "manufacturing" }] },
      { id: "environment", label: "Environment", writes: [{ key: "industry", value: "environment" }] },
      { id: "worker-safety", label: "Worker safety", writes: [{ key: "industry", value: "worker safety" }] },
      { id: "supply-chain", label: "Supply chain", writes: [{ key: "industry", value: "supply chain" }] },
    ],
    id: "query-industry-context",
    maxDismissals: 2,
    maxShows: 3,
    placement: "query-results",
    question: "This question reads like an operating issue. Should Geode weight that context next time?",
    skipIfAnsweredKeys: ["industry", "modelE.industry"],
    teachingLine: "Geode can keep the same statutes in view while changing which risks rise first.",
  },
  {
    action: "regulation_opened",
    answers: [
      { id: "compliance", label: "Compliance", writes: [{ key: "role", value: "Compliance" }] },
      { id: "legal-ops", label: "Legal ops", writes: [{ key: "role", value: "Legal operations" }] },
      { id: "government-affairs", label: "Government affairs", writes: [{ key: "role", value: "Government affairs" }] },
      { id: "regulatory-intelligence", label: "Regulatory intelligence", writes: [{ key: "role", value: "Regulatory intelligence" }] },
    ],
    id: "regulation-reading-role",
    maxDismissals: 2,
    maxShows: 3,
    placement: "regulation-detail",
    question: "You opened the full rule. Which seat are you reading from right now?",
    skipIfAnsweredKeys: ["role", "modelE.role"],
    teachingLine: "The same rule can become a board risk, legal citation, or operating checklist depending on the reader.",
  },
  {
    action: "forum_thread_created",
    answers: [
      { id: "interpretation", label: "Interpretation", writes: [{ key: "forumFocus", value: "interpretation" }] },
      { id: "enforcement", label: "Enforcement", writes: [{ key: "forumFocus", value: "enforcement" }] },
      { id: "case-study", label: "Case studies", writes: [{ key: "forumFocus", value: "case-study" }] },
      { id: "expert", label: "Expert answers", writes: [{ key: "forumFocus", value: "ask-an-expert" }] },
    ],
    id: "forum-thread-focus",
    maxDismissals: 2,
    maxShows: 3,
    placement: "forum-feed",
    question: "Your first thread creates a forum lens. Which conversations should rise first?",
    teachingLine: "Geode can separate practical judgment, enforcement risk, and expert interpretation instead of flattening them.",
  },
  {
    action: "forum_reply_created",
    answers: [
      { id: "official-first", label: "Official sources", writes: [{ key: "answerStyle", value: "official-first" }] },
      { id: "peer-first", label: "Peer judgment", writes: [{ key: "answerStyle", value: "peer-first" }] },
      { id: "balanced", label: "Balanced", writes: [{ key: "answerStyle", value: "balanced" }] },
    ],
    id: "answer-style-preference",
    maxDismissals: 2,
    maxShows: 3,
    placement: "forum-thread",
    question: "That reply adds a point of view. When answers compete, what should Geode privilege?",
    teachingLine: "Geode can keep official authority and field interpretation distinct instead of blending them together.",
  },
  {
    action: "forum_vote_cast",
    answers: [
      { id: "practical", label: "Practical usefulness", writes: [{ key: "voteLens", value: "practical" }] },
      { id: "legal", label: "Legal precision", writes: [{ key: "voteLens", value: "legal" }] },
      { id: "clarity", label: "Clarity", writes: [{ key: "voteLens", value: "clarity" }] },
    ],
    id: "vote-signal-meaning",
    maxDismissals: 1,
    maxShows: 2,
    placement: "forum-thread",
    question: "That vote is a signal. What made the contribution useful?",
    teachingLine: "A vote can mean precision, usefulness, or clarity. Geode can learn the difference without asking again.",
  },
];
