"""Editable deterministic taxonomy for CCR industry filtering."""

from __future__ import annotations

TAXONOMY_VERSION = "1.0.0"

DEFAULT_CCR_TAXONOMY: dict[str, object] = {
    "version": TAXONOMY_VERSION,
    "rules": [
        {
            "rule_id": "agency_air_quality",
            "source": "agency",
            "match_fields": ["department", "department_normalized", "agency", "agency_normalized"],
            "any_terms": [
                "air pollution control division",
                "air quality control commission",
            ],
            "citation_prefixes": ["5 CCR 1001"],
            "industry_tags": [
                "manufacturing",
                "utilities",
                "oil_gas",
                "transportation_warehousing",
            ],
            "topic_tags": [
                "environment",
                "air_quality",
                "emissions",
                "permitting",
                "reporting",
                "inspection",
                "enforcement",
            ],
            "domain_tags": [
                "environmental_air",
                "building_fire_industrial_operations",
                "general_manufacturing",
            ],
            "confidence": 0.95,
            "reason": "Air-quality and emissions rules commonly affect industrial sources.",
        },
        {
            "rule_id": "agency_water_quality",
            "source": "agency",
            "match_fields": ["department", "department_normalized", "agency", "agency_normalized"],
            "any_terms": [
                "water quality control commission",
                "water quality control division",
                "drinking water",
                "water and wastewater",
            ],
            "citation_prefixes": ["5 CCR 1002", "5 CCR 1003", "5 CCR 1004"],
            "industry_tags": ["manufacturing", "utilities", "mining", "agriculture"],
            "topic_tags": [
                "environment",
                "water_quality",
                "drinking_water",
                "permitting",
                "reporting",
                "inspection",
            ],
            "domain_tags": [
                "environmental_water",
                "general_manufacturing",
            ],
            "confidence": 0.9,
            "reason": "Water-quality and discharge rules can apply to industrial operations.",
        },
        {
            "rule_id": "agency_waste_management",
            "source": "agency",
            "match_fields": ["department", "department_normalized", "agency", "agency_normalized"],
            "any_terms": [
                "hazardous materials and waste management",
                "hazardous waste commission",
                "solid and hazardous waste commission",
                "solid waste",
            ],
            "citation_prefixes": ["5 CCR 1007"],
            "industry_tags": ["manufacturing", "administrative_support", "healthcare"],
            "topic_tags": [
                "environment",
                "solid_waste",
                "hazardous_waste",
                "environmental_cleanup",
                "recordkeeping",
                "inspection",
                "enforcement",
            ],
            "domain_tags": [
                "environmental_waste",
                "chemicals_exposure",
                "general_manufacturing",
            ],
            "confidence": 0.95,
            "reason": "Hazardous and solid waste rules are high-value manufacturing filters.",
        },
        {
            "rule_id": "agency_radiation_exposure",
            "source": "agency",
            "match_fields": ["department", "department_normalized", "agency", "agency_normalized"],
            "any_terms": ["radiation control", "x-ray", "radioactive material"],
            "industry_tags": ["manufacturing", "healthcare"],
            "topic_tags": ["public_health", "radiation_control", "inspection", "enforcement"],
            "domain_tags": [
                "chemicals_exposure",
                "workplace_health",
                "general_manufacturing",
            ],
            "confidence": 0.75,
            "reason": "Radiation-control metadata can indicate exposure-control obligations.",
        },
        {
            "rule_id": "agency_labor_standards",
            "source": "agency",
            "match_fields": ["department", "department_normalized", "agency", "agency_normalized"],
            "any_terms": [
                "labor standards",
                "division of labor standards",
                "employment",
                "labor and employment",
            ],
            "citation_prefixes": ["7 CCR 1103"],
            "industry_tags": ["manufacturing", "small_business"],
            "topic_tags": [
                "labor_employment",
                "wages_hours",
                "paid_leave",
                "child_labor",
                "recordkeeping",
            ],
            "domain_tags": ["labor_employment", "wage_hour", "general_manufacturing"],
            "confidence": 0.85,
            "reason": "Labor standards apply cross-sector, including manufacturing employers.",
        },
        {
            "rule_id": "agency_workers_compensation",
            "source": "agency",
            "match_fields": ["department", "department_normalized", "agency", "agency_normalized"],
            "any_terms": ["workers' compensation", "workers compensation"],
            "citation_prefixes": ["7 CCR 1101"],
            "industry_tags": ["manufacturing", "small_business"],
            "topic_tags": ["labor_employment", "workers_compensation", "workplace_safety"],
            "domain_tags": [
                "occupational_safety",
                "workplace_health",
                "labor_employment",
                "general_manufacturing",
            ],
            "confidence": 0.8,
            "reason": "Workers' compensation metadata is relevant to workplace operations.",
        },
        {
            "rule_id": "agency_public_utilities",
            "source": "agency",
            "match_fields": ["department", "department_normalized", "agency", "agency_normalized"],
            "any_terms": ["public utilities commission", "utilities commission"],
            "citation_prefixes": ["4 CCR 723"],
            "industry_tags": ["utilities", "manufacturing", "oil_gas"],
            "topic_tags": ["energy", "utility_regulation", "pipeline_safety"],
            "domain_tags": [
                "energy_utilities",
                "building_fire_industrial_operations",
                "general_manufacturing",
            ],
            "confidence": 0.85,
            "reason": "Utility and tariff rules can affect industrial energy users.",
        },
        {
            "rule_id": "agency_oil_gas_energy",
            "source": "agency",
            "match_fields": ["department", "department_normalized", "agency", "agency_normalized"],
            "any_terms": [
                "oil and gas conservation",
                "energy and carbon management",
                "oil and public safety",
            ],
            "industry_tags": ["oil_gas", "utilities", "manufacturing"],
            "topic_tags": ["energy", "oil_gas", "pipeline_safety", "natural_resources"],
            "domain_tags": [
                "energy_utilities",
                "transportation_hazmat",
                "building_fire_industrial_operations",
                "general_manufacturing",
            ],
            "confidence": 0.85,
            "reason": "Energy and oil/gas rules can affect fuel, storage, and industrial sites.",
        },
        {
            "rule_id": "agency_mining_reclamation",
            "source": "agency",
            "match_fields": ["department", "department_normalized", "agency", "agency_normalized"],
            "any_terms": [
                "reclamation mining and safety",
                "mined land reclamation",
                "division of reclamation",
                "minerals",
            ],
            "industry_tags": ["mining", "manufacturing"],
            "topic_tags": ["energy", "mining", "natural_resources", "environment"],
            "domain_tags": [
                "mining_minerals_natural_resources",
                "environmental_waste",
                "general_manufacturing",
            ],
            "confidence": 0.85,
            "reason": "Mining and mineral rules are adjacent to raw-material supply chains.",
        },
        {
            "rule_id": "agency_transport_hazmat",
            "source": "agency",
            "match_fields": ["department", "department_normalized", "agency", "agency_normalized"],
            "any_terms": [
                "transportation",
                "motor carrier",
                "hazardous materials",
                "commercial vehicle",
            ],
            "industry_tags": ["transportation_warehousing", "manufacturing"],
            "topic_tags": ["transportation", "commercial_vehicles", "motor_vehicles"],
            "domain_tags": ["transportation_hazmat", "general_manufacturing"],
            "confidence": 0.7,
            "reason": "Transportation and motor-carrier metadata can indicate shipping duties.",
        },
        {
            "rule_id": "agency_fire_building_industrial",
            "source": "agency",
            "match_fields": ["department", "department_normalized", "agency", "agency_normalized"],
            "any_terms": [
                "fire prevention and control",
                "fire safety",
                "building codes",
                "boiler inspection",
                "pressure vessel",
            ],
            "industry_tags": ["manufacturing", "construction"],
            "topic_tags": ["public_health", "building_codes", "construction_standards"],
            "domain_tags": [
                "building_fire_industrial_operations",
                "occupational_safety",
                "general_manufacturing",
            ],
            "confidence": 0.8,
            "reason": "Fire, building, boiler, and pressure-vessel rules affect facilities.",
        },
        {
            "rule_id": "keyword_air_emissions",
            "source": "keyword",
            "match_fields": ["title", "rule_name", "agency", "agency_normalized", "ccr_citation"],
            "any_terms": [
                "air quality",
                "emission",
                "stationary source",
                "opacity",
                "particulate",
                "volatile organic",
                "greenhouse gas",
            ],
            "industry_tags": ["manufacturing", "utilities", "oil_gas"],
            "topic_tags": ["environment", "air_quality", "emissions"],
            "domain_tags": ["environmental_air", "general_manufacturing"],
            "confidence": 0.7,
            "reason": "Air/emissions keywords appeared in available CCR metadata.",
        },
        {
            "rule_id": "keyword_water_discharge",
            "source": "keyword",
            "match_fields": ["title", "rule_name", "agency", "agency_normalized"],
            "any_terms": [
                "wastewater",
                "stormwater",
                "water quality",
                "discharge",
                "effluent",
                "drinking water",
            ],
            "industry_tags": ["manufacturing", "utilities"],
            "topic_tags": ["environment", "water_quality", "drinking_water"],
            "domain_tags": ["environmental_water", "general_manufacturing"],
            "confidence": 0.7,
            "reason": "Water/discharge keywords appeared in available CCR metadata.",
        },
        {
            "rule_id": "keyword_waste_hazmat",
            "source": "keyword",
            "match_fields": ["title", "rule_name", "agency", "agency_normalized"],
            "any_terms": [
                "hazardous waste",
                "solid waste",
                "universal waste",
                "recycling",
                "remediation",
                "cleanup",
                "landfill",
            ],
            "industry_tags": ["manufacturing", "administrative_support"],
            "topic_tags": ["environment", "solid_waste", "hazardous_waste"],
            "domain_tags": [
                "environmental_waste",
                "chemicals_exposure",
                "general_manufacturing",
            ],
            "confidence": 0.75,
            "reason": "Waste/hazardous-material keywords appeared in CCR metadata.",
        },
        {
            "rule_id": "keyword_labor_employment",
            "source": "keyword",
            "match_fields": ["title", "rule_name", "agency", "agency_normalized"],
            "any_terms": [
                "minimum wage",
                "overtime",
                "paid leave",
                "employee",
                "employment",
                "labor standards",
                "wage",
            ],
            "industry_tags": ["manufacturing", "small_business"],
            "topic_tags": ["labor_employment", "wages_hours", "paid_leave"],
            "domain_tags": ["labor_employment", "wage_hour", "general_manufacturing"],
            "confidence": 0.7,
            "reason": "Labor/employment keywords appeared in CCR metadata.",
        },
        {
            "rule_id": "keyword_exposure_controls",
            "source": "keyword",
            "match_fields": ["title", "rule_name", "agency", "agency_normalized"],
            "any_terms": [
                "chemical",
                "toxic",
                "exposure",
                "asbestos",
                "lead-based paint",
                "silica",
                "radiation",
            ],
            "industry_tags": ["manufacturing", "construction", "healthcare"],
            "topic_tags": ["public_health", "workplace_safety", "radiation_control"],
            "domain_tags": [
                "chemicals_exposure",
                "workplace_health",
                "general_manufacturing",
            ],
            "confidence": 0.65,
            "reason": "Chemical/exposure keywords appeared in CCR metadata.",
        },
        {
            "rule_id": "keyword_product_materials",
            "source": "keyword",
            "match_fields": ["title", "rule_name", "agency", "agency_normalized"],
            "any_terms": [
                "product",
                "labeling",
                "packaging",
                "consumer protection",
                "weights and measures",
                "metrology",
            ],
            "industry_tags": ["manufacturing", "wholesale_trade", "retail_trade"],
            "topic_tags": ["business_regulation", "consumer_protection", "trade_practices"],
            "domain_tags": ["materials_product_compliance", "general_manufacturing"],
            "confidence": 0.6,
            "reason": "Product/materials compliance keywords appeared in CCR metadata.",
        },
    ],
}
